# Generated by Django 2.2.2 on 2019-06-21 07:05

from django.db import migrations, models
import django.db.models.deletion
import ticket_system.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name of event')),
                ('start_date_and_time', models.DateTimeField(verbose_name='Start date and time')),
                ('end_date_and_time', models.DateTimeField(verbose_name='End date and time')),
                ('total_student_tickets', models.IntegerField(verbose_name='Available student tickets')),
                ('total_normal_tickets', models.IntegerField(verbose_name='Available normal tickets')),
                ('total_premium_tickets', models.IntegerField(verbose_name='Available premium tickets')),
                ('total_vip_tickets', models.IntegerField(verbose_name='Available vip tickets')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Price')),
                ('type_ticket', models.CharField(choices=[('STUDENT', ticket_system.models.TypeTickets('STUDENT')), ('NORMAL', ticket_system.models.TypeTickets('NORMAL')), ('PREMIUM', ticket_system.models.TypeTickets('PREMIUM')), ('VIP', ticket_system.models.TypeTickets('VIP'))], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_client', models.CharField(max_length=120, verbose_name='First name')),
                ('last_name_client', models.CharField(max_length=120, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=45, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Phone number')),
                ('date_and_time_of_reservation', models.DateTimeField(verbose_name='Date and time of reservation')),
                ('type_ticket', models.CharField(choices=[('STUDENT', 'STUDENT'), ('NORMAL', 'NORMAL'), ('PREMIUM', 'PREMIUM'), ('VIP', 'VIP')], max_length=7)),
                ('state', models.CharField(choices=[('RESERVED', ticket_system.models.States('RESERVED')), ('PAID', ticket_system.models.States('PAID')), ('CANCELED', ticket_system.models.States('CANCELED'))], default='RESERVED', max_length=7)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='ticket_system.Event', verbose_name='Event')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket', to='ticket_system.Ticket', verbose_name='ticketit')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='normal_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='normal_ticket', to='ticket_system.Ticket', verbose_name='Normal ticket'),
        ),
        migrations.AddField(
            model_name='event',
            name='premium_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='premium_ticket', to='ticket_system.Ticket', verbose_name='Premium ticket'),
        ),
        migrations.AddField(
            model_name='event',
            name='student_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_ticket', to='ticket_system.Ticket', verbose_name='Student ticket'),
        ),
        migrations.AddField(
            model_name='event',
            name='vip_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vip_ticket', to='ticket_system.Ticket', verbose_name='Vip icket'),
        ),
    ]
