# Generated by Django 2.2.2 on 2019-06-17 18:32

from django.db import migrations, models
import ticket_system.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name of event')),
                ('start_date_and_time', models.DateField(verbose_name='Start date and time')),
                ('end_date_and_time', models.DateField(verbose_name='End date and time')),
                ('available_student_ticets', models.IntegerField(verbose_name='Available student ticets')),
                ('available_normal_ticets', models.IntegerField(verbose_name='Available normal ticets')),
                ('available_premium_ticets', models.IntegerField(verbose_name='Available premium ticets')),
                ('available_vip_ticets', models.IntegerField(verbose_name='Available vip ticets')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ticet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Price')),
                ('ticet_type', models.CharField(choices=[(ticket_system.models.TypeTicets(1), 1), (ticket_system.models.TypeTicets(2), 2), (ticket_system.models.TypeTicets(3), 3), (ticket_system.models.TypeTicets(4), 4)], max_length=1)),
                ('date_and_time_of_reservation', models.DateField(verbose_name='Date and time of reservation')),
            ],
        ),
    ]
