# Generated by Django 2.2.2 on 2019-06-19 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket', to='ticket_system.Ticket', verbose_name='ticket'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='type_ticket',
            field=models.CharField(choices=[('STUDENT', 'STUDENT'), ('NORMAL', 'NORMAL'), ('PREMIUM', 'PREMIUM'), ('VIP', 'VIP')], default=1, max_length=7),
            preserve_default=False,
        ),
    ]
